#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_ai = env_modules.Clone()

# Core AI module source files
env_ai.add_source_files(env.modules_sources, "*.cpp")

# Editor-only sources (status indicator plugin)
if env.editor_build:
    env_ai.add_source_files(env.modules_sources, "editor/*.cpp")
